sudo: required

language: bash

services:
  - docker

before_script:
  - docker -v
  - docker build -t keboola/ex-gooddata .
  - docker run --rm  keboola/ex-gooddata composer install
  - docker run --rm  keboola/ex-gooddata composer phpcs

script:
  - >
    docker run --rm
    -e EX_GD_USERNAME
    -e EX_GD_PASSWORD
    -e EX_GD_PROJECT
    -e EX_GD_HOST
    -e EX_GD_ALT_USERNAME
    -e EX_GD_ALT_PASSWORD
    -e EX_GD_ALT_PROJECT
    -e EX_GD_ALT_HOST
    keboola/ex-gooddata composer test

after_success:
  - docker images

deploy:
  provider: script
  script: ./deploy.sh
  on:
    tags: true
