version: "2"

services:

  tests:
    build: .
    image: keboola/gooddata-extractor
    tty: true
    stdin_open: true
    command: composer build
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      - EX_GD_PASSWORD
      - EX_GD_PROJECT
      - EX_GD_USERNAME
      - EX_GD_HOST
      - EX_GD_ALT_USERNAME
      - EX_GD_ALT_PASSWORD
      - EX_GD_ALT_PROJECT
      - EX_GD_ALT_HOST
