version: "2"

services:

  tests:
    build: .
    image: keboola/gooddata-extractor
    tty: true
    stdin_open: true
    command: ./tests.sh
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      - KBC_URL
      - KBC_TOKEN
      - GD_PID
      - GD_PROVISIONING_URL
