version: "2"

services:

  tests:
    build: .
    image: keboola/gooddata-extractor
    tty: true
    stdin_open: true
    command: composer build
    volumes:
      - ./:/code
    working_dir: /code
    environment:
      - EX_GD_PASSWORD
      - EX_GD_PROJECT
      - EX_GD_USERNAME
      - GD_PROVISIONING_PID
      - GD_PROVISIONING_URL
      - KBC_TOKEN
      - KBC_URL
